### ISSUE TITLE
deploy 자동화

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Serverless#3]
- [ ] master로 푸쉬된 코드에게 deploy(functions만) 자동화

**Comment by sunwupark** [comment]
![image](https://github.com/FileGround-CloudComputing/FileGround-Serverless/assets/52268188/aed744b9-ff19-46ec-b072-c3fb6e67b2d9)

일단 제 개인 repo에서는 동작하는것을 확인하였습니다. 여기에 추가하겠습니다

**Comment by sunwupark** [comment]
File-Ground severless settings에 secret 키 추가하였습니다. 약 7가지 추가하였습니다

**Comment by sunwupark** [comment]
sunwupark-patch-1 에다가 추가하였습니다

**Comment by gene-ss** [comment]
#7 를 통해 병합
