### ISSUE TITLE
github action 실패

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Serverless#8]
https://github.com/FileGround-CloudComputing/FileGround-Serverless/actions/runs/5169626328/jobs/9311991991
참조

**Comment by sunwupark** [comment]
제 repository와 비교를 해본결과 package.json 파일에 firebase-tools가 빠진것을 확인했습니다. 한번 pull request를 했는데 시도해봐도 될까요

**Comment by sunwupark** [comment]
아? 왜 바로 들어가지.. 죄송합니다..

**Comment by sunwupark** [comment]
일단 다시 돌려봤을때 성공하는거 확인했습니다!
